site_name: xDSL
site_url: https://xdsl.dev
site_description: xDSL -- a Python-native compiler framework
site_author: xDSL developers
copyright: Copyright &copy xDSL developers
repo_name:  xdslproject/xdsl
repo_url: https://github.com/xdslproject/xdsl

strict: true

theme:
  name: "material"
  logo: assets/img/logos/xdsl-transparent-single.png
  favicon: assets/img/logos/xdsl-transparent-single.png
  locale: en
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: xdsl
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - meta
  - sane_lists
  - smarty
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.saneheaders
  - pymdownx.superfences
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

plugins:
- search
- awesome-nav
- blog:
    blog_dir: news
    blog_toc: true
- rss:
    match_path: (events|news/posts)/.*
    date_from_meta:
      as_creation: date
    categories:
      - categories
      - tags
    feeds_filenames:
      rss_created: feed.xml
      rss_updated: feed-updated.xml

extra:
  social:
    - icon: material/rss
      link: /feed.xml
      name: Subscribe to our RSS Feed
    - icon: material/chat
      link: https://xdsl.zulipchat.com/
      name: Chat on Zulip
    - icon: material/github
      link: https://github.com/xdslproject
      name: Contribute on Github
