site_name: xDSL
site_url: https://xdsl.readthedocs.io/
site_description: xDSL -- a Python-native compiler framework
site_author: xDSL developers
copyright: Copyright &copy xDSL developers
repo_name:  xdslproject/xdsl
repo_url: https://github.com/xdslproject/xdsl

# strict: true

theme:
  name: "material"
  # custom_dir: overrides
  logo: assets/img/logos/xdsl-transparent-single.png
  favicon: assets/img/logos/xdsl-transparent-single.png
  # logo: assets/img/logos/Logo.png
  # favicon: assets/img/logos/Logo.png
  extra_css:
  - stylesheets/extra.css
  locale: en
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
  # palette:
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: black
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to light mode

plugins:
- search
- blog:
    blog_toc: true
- rss:
    match_path: blog/posts/.*
    date_from_meta:
      as_creation: date
    categories:
      - categories
      - tags

    feeds_filenames:
      rss_created: feed.xml
      rss_updated: feed-updated.xml
nav:
  - Home: index.md
  - News: blog/index.md
  - Workshop: "https://xdsl.readthedocs.io/stable/marimo"
  - Community:
    - ASPLOS: events/ASPLOS.md
    - Euro-Par Workshop: events/europar.md
    - HiPEAC: events/HiPEAC.md
    - MLIR Winter School: events/winter-school.md
  - Developers:
    - Application: developers/appdev.md
    - DSL: developers/dsldev.md
  - About:
    - Challenge: about/challenge.md
    - Partners: about/partners.md
    - Excalibur: about/excalibur.md
  - Documentation: "https://xdsl.readthedocs.io/stable/"

extra:
  social:
    - icon: material/rss
      link: /feed.xml
      name: Subscribe to our RSS Feed
    - icon: material/chat
      link: https://xdsl.zulipchat.com/
      name: Chat on Zulip
    - icon: material/github
      link: https://github.com/xdslproject
      name: Contribute on Github
