nav:
  - index.md
  - Tutorial Notebooks: "https://xdsl.readthedocs.io/stable/marimo/"
  - API Reference: "https://xdsl.readthedocs.io/stable/reference/"
  - User Guide: "https://xdsl.readthedocs.io/stable/guides/mlir_interoperation/"
  - news/index.md
  - events
  - about
