nav:
  - index.md
  - Getting Started: "https://docs.xdsl.dev/"
  - Tutorial Notebooks: "https://docs.xdsl.dev/marimo/"
  - API Reference: "https://docs.xdsl.dev/reference/"
  - User Guide: "https://docs.xdsl.dev/guides/mlir_interoperation/"
  - news/index.md
  - events
  - about
